# Generated by Django 4.0 on 2021-12-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('atomic_number', models.IntegerField(unique=True)),
                ('symbol', models.CharField(max_length=250)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('atomic_weight', models.FloatField()),
                ('melting_point', models.IntegerField()),
                ('boiling_point', models.IntegerField()),
                ('electron_configuration', models.CharField(max_length=250)),
            ],
        ),
    ]
