# Generated by Django 4.0 on 2021-12-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='discovery_year',
            field=models.CharField(default='', max_length=5),
        ),
    ]
