# Generated by Django 4.0 on 2021-12-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_elements_boiling_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='discovery_year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
