# Generated by Django 4.0 on 2021-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_elements_discovery_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='electron_configuration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
